import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "../components/Navbar";
import Footer from "../components/Footer";

const customFont1 = localFont({
  src: "./fonts/Catamaran-Black.ttf",
  variable: "--catamaran-font"
});

const customFont2 = localFont({
  src: "./fonts/Raleway-Regular.ttf",
  variable: "--raleway-font"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${customFont1.variable} ${customFont2.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
